theme = "terafox"

[editor]
line-number = "relative"
rulers = [100]
color-modes = true

# Show hidden/dotfiles in the file picker.
[editor.file-picker]
hidden = false

[keys.normal]
"C-b" = ":sh latexmk -pdf -interaction=nonstopmode -outdir=out main.tex"
# inc included files, stderr > stdout, last line to ignore warnings
"C-c" = ":sh sh -c 'texcount -total -inc -brief -quiet main.tex 2>&1 | tail -n 1'"
"C-p" = ":sh xdg-open out/main.pdf"
